logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE

spring:
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true

blog:
  account-svc-endpoint: ${ACCOUNT_SERVICE_ENDPOINT:http://localhost:8081}
  post-svc-endpoint: ${POST_SERVICE_ENDPOINT:http://localhost:8082}
  page-svc-endpoint: ${PAGE_SERVICE_ENDPOINT:http://localhost:8083}
